name: Create Tag on Version Change

on:
  push:
    paths:
      - src/PlutoTV/__init__.py
    branches:
      - main

permissions:
  contents: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from file
        id: get_version
        run: |
          VERSION=$(grep -oP '(?<=__version__ = ")[^"]+' src/PlutoTV/__init__.py)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ steps.get_version.outputs.version }}$"; then
            echo "Tag v${{ steps.get_version.outputs.version }} already exists."
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Create and push tag
        if: steps.check_tag.outputs.skip != 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

